version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hard-rock-money-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/budget_db
      - NEXTAUTH_SECRET=supersecret
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db
    networks:
      - budget-network

  db:
    image: postgres:15-alpine
    container_name: hard-rock-money-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - budget-network
    ports:
      - "5432:5432"

networks:
  budget-network:
    driver: bridge

volumes:
  postgres_data:
